### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ptahdunbar** [jaesius/jemiahsius.com#2]
# TODO
- [ ] Add favicon to site
- [ ] Update website copy for about me section
- [ ] Update contact form sub heading copy
- [ ] Finalize page styling (colors, hover states)
- [ ] Add 6 portfolio items (including thumbnails, large image and description
- [ ] Add SSL to site using [letsencrypt](https://letsencrypt.org/)
- [ ] Fix JavaScript console errors
- [ ] Validate and cleanup HTML with https://validator.w3.org/
- [ ] Apply recommendations and improvements with https://developers.google.com/speed/pagespeed/insights/
- [ ] Validate CSS on http://csslint.net/
