### ISSUE TITLE
Code Review Mobile

### ISSUE THREAD

**Issue by ptahdunbar** [jaesius/jemiahsius.com#3]
# TODO
- [ ] Adjust viewport for mobile
- [ ] Adjust button sizes
- [ ] Adjust text sizes for readability
- [ ] Adjust menu to use hamburger icon (click to open)
